INSERT INTO appliance (name, country, manufacturer, online, instalment) VALUES
('Телевизор', 'Россия', 'Samsung', true, true),
('Телевизор', 'Беларусь', 'DEXP', true, false),
('Телевизор', 'Китай', 'TCL', false, true),
('Смартфон', 'Китай', 'Apple', true, true),
('Смартфон', 'Китай', 'Xiaomi', true, false),
('Смартфон', 'Вьетнам', 'Samsung', false, true),
('Пылесос', 'Китай', 'Polaris', true, false),
('Пылесос', 'Вьетнам', 'Samsung', true, true),
('Пылесос', 'Германия', 'Thomas', false, true),
('Холодильник', 'Китай', 'DEXP', true, false),
('Холодильник', 'Россия', 'Haier', true, true),
('Холодильник', 'Узбекистан', 'Samsung', true, true),
('ПК', 'Китай', 'Acer', true, true),
('ПК', 'Китай', 'Ardor', true, true),
('ПК', 'Китай', 'DEXP', true, true);
